alert-updates: main
debug: false
check-proxies: true
enable-onJoin: true

local-db: true
persistence-days: 60

mysql-enable: false
mysql-database: jdbc:mysql://localhost:3306/minecraft
mysql-user: root
mysql-password: root
mysql-table: player-tracker

minebans-enable: false
minebans-API-key: 0

mcbans-enable: false
mcbans-API-key: 0

mcbouncer-enable: false
mcbouncer-API-key: 0

glizer-enable: false
glizer-API-key: 0

untraceable:
  - Notch
  - 127.0.0.1
  